name: Challenge3

env: 
  ARTIFACT_NAME: 'artifact'

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Run script
      run: python hello.py
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ./${{env.artifact_name}}
        path: .

      